### ISSUE TITLE
Undef StanODEData unless CmdStan required pre DiffEqBayes

### ISSUE THREAD

**Issue by robertfeldt** [SciML/DiffEqBayes.jl#143]
`StanODEData` is undefined unless `CmdStan` is required before `DiffEqBayes`. Also it is not exported so the example in the README doesn't work which might be confusing for newcomers.

This shows the problems:
```
feldt:~$ julia
...
julia> using DiffEqBayes

julia> DiffEqBayes.StanODEData()
ERROR: UndefVarError: StanODEData not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:13
 [2] top-level scope at REPL[3]:1

julia> exit()
feldt:~$ julia
...
julia> using CmdStan

julia> using DiffEqBayes

julia> StanODEData()
ERROR: UndefVarError: StanODEData not defined
Stacktrace:
 [1] top-level scope at REPL[3]:1

julia> DiffEqBayes.StanODEData()
DiffEqBayes.StanODEData()

julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

**Comment by Vaibhavdixit02** [comment]
Yes that is intentional, https://github.com/SciML/DiffEqBayes.jl/blob/31353ed3b8c9e028505e5102acb80631d0305161/src/DiffEqBayes.jl#L14. 

I missed responding to your last issue, sorry about that, did you get that resolved?

**Comment by robertfeldt** [comment]
But the example at the end of the README will not work without exporting StanODEData, or am I missing something?

I also wonder if there is some way to have some of the data (i.e. some of the variables on the ODE) be latent (unobserved)? Would be great with an example of that, if so.
