### ISSUE TITLE
Turing tests failing on master

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqBayes.jl#152]
https://travis-ci.org/github/SciML/DiffEqBayes.jl/jobs/674686439#L631

It looks like Turing had a breaking change in its latest patch release? Let's figure out what's going on here. @mohamed82008 @Vaibhavdixit02

**Comment by mohamed82008** [comment]
Looks like a Turing-AHMC issue CC: @xukai92.

**Comment by xukai92** [comment]
It's a breaking change from AHMC. There is a typo in the deprecation code. Let me fix it.

**Comment by xukai92** [comment]
Should be fixed by https://github.com/TuringLang/AdvancedHMC.jl/pull/193. I will make a new release once the PR is merged. Hopefully DiffEqBayes will only throw deprecation warnings after then.

**Comment by Richert** [comment]
While Turing tests fail for me in version 0.10.1, they pass in version  0.11.0.
Current dependencies of DiffEqBayes require Turing <= 0.10.1, however.
A dependency update would be much appreciated!
