### ISSUE TITLE
Parallel abc_inference

### ISSUE THREAD

**Issue by claudio20497** [SciML/DiffEqBayes.jl#187]
Hello,

I see that parallelization is available in the [ApproxBayes.jl](https://github.com/marcjwilliams1/ApproxBayes.jl#parallelism) package, by using `parallel` keyword. Is there a way to activate parallelism also in `abc_inference` ? I tried to play with its `kwargs` argument with no results..-

**Comment by Vaibhavdixit02** [comment]
@claudio20497 once https://github.com/JuliaRegistries/General/pull/25070 goes in the new release can be used and you can pass in the `parallel` kwarg to use multithreading with `abc_inference`
