### ISSUE TITLE
Updates for StanSample.jl

### ISSUE THREAD

**Issue by goedman** [SciML/DiffEqBayes.jl#219]
Hi @Vaibhavdixit02 

Just successfully ran the test suite for StanSample.jl (the compathelper branch with all you latest changes)!

I had to remove CmdStan (for now I replaced it with StanSample, but I don't think you need that there) from stan_string.jl and export stan_string from DiffEqBayes.  But you might have a better way.

**Comment by Vaibhavdixit02** [comment]
Yes in the DiffEqBayes PR I made these changes.

**Comment by goedman** [comment]
Just successfully ran the Stan tests on the updated master of DiffEqBayes.

I also experimented with the 4 parameter model by injecting more noise and widening the priors. That also behaves ok.

For StatisticalRethinking chapter 16 I would like to use DiffEqBayes but really can't use it in it's current form. It simply has too many dependencies.

I wonder if the current DiffEqBayes should just target Turing and if there is interest in splitting off a DiffEqBayesStan.jl. Maybe the same argument could be made for DynamicHMC. 

If you feel that goes too far outside the objectives of SciML, I could create a DiffEqBayesStan.jl in StanJulia.

**Comment by Vaibhavdixit02** [comment]
We had switched to `require` for DynamicHMC and CmdStan but I moved StanSample out of it because it seems to have less issues in installation to me, we can move it back but I don't think that's what you want. I am not sure it's too many dependencies, the motivation was to have a unified interface for several PPL packages through this package so that has been the approach so far. I am curious if you can specify a bit more what seems excessive here to you we can maybe take care of that?

**Comment by goedman** [comment]
Thanks Vaibhav, you are of course correct that the objectives of DiffEqBayes are much broader than my question.

My main problem has been (time and time again) that pulling in too many dependencies creates version conflicts and/or compilation warnings and/or package downgrades. This has gotten better over the last few years but in just trying to help out here showed me these issues are still there.

It certainly doesn't help that I prefer to develop on nightly. Currently (last time I tried it a few days ago) DiffEqBayes only works on Julia 1.6, not on 1.7/1.8. For very good reasons!

CmdStan and StanJulia all require Stan's cmdstan executable to be installed and hence to use Stan behind Requires makes perfect sense. Requesting to put all 3 behind Requires seems ridiculous to me. Hence my thought for a StanJulia sibling of DiffEqBayes.jl.

**Comment by Vaibhavdixit02** [comment]
>CmdStan and StanJulia all require Stan's cmdstan executable to be installed and hence to use Stan behind Requires makes perfect sense.

Right yeah, let's move it back in there then.

>Requesting to put all 3 behind Requires seems ridiculous to me.

We still keep Turing outside it just DynamicHMC and Stan behind it. 

>Hence my thought for a StanJulia sibling of DiffEqBayes.jl.

I am a little hesitant since this project is already not heavily developed so splitting will thin both the users and dev effort. I get your pain for version incompatibilities but to be honest DiffEqBayes is probably one with least issues as compared to some other packages in the SciML ecosystem. I am not looking to counter you though, so feel free to move ahead if you do think it's the best way forward we can always just link back to this repo so users can discover it.

**Comment by ChrisRackauckas** [comment]
It's not the most user facing repository. I mean, it kind of is a higher level interface for people who don't want to dig into PPLs, but the most useful thing has actually been for devs to benchmark between PPLs.

**Comment by goedman** [comment]
> On Jul 13, 2021, at 09:19, Christopher Rackauckas ***@***.***> wrote:
> 
> It's not the most user facing repository. I mean, it kind of is a higher level interface for people who don't want to dig into PPLs, but the most useful thing has actually been for devs to benchmark between PPLs.


True, but the introduction of Symbolics.jl and `build_function` for me is a game changer. For the first time in well over 20 years I did not *need* to renew my Mathematica license.

> On Jul 13, 2021, at 09:17, Vaibhav Kumar Dixit ***@***.***> wrote:
> Hence my thought for a StanJulia sibling of DiffEqBayes.jl.
> 
> I am a little hesitant since this project is already not heavily developed so splitting will thin both the users and dev effort. I get your pain for version incompatibilities but to be honest DiffEqBayes is probably one with least issues as compared to some other packages in the SciML ecosystem. I am not looking to counter you though, so feel free to move ahead if you do think it's the best way forward we can always just link back to this repo so users can discover it.
> 
There are some spectacular ideas in DifferentialEquations.jl, ModelingToolkit.jl and DiffEqBayes.jl. In the past I had a separate section `Examples_DiffEqBayes` in Stan.jl (which I use to showcase the capabilities of the StanJulia suite and for testing all its examples and packages) but found those examples failed on Julia versions not fully released.

There is a huge uptick in interest in Stan and ODEs, some Julia users would over time switch from a DiffEqBayesStan to using Turing or DynamicHMC and to DiffEqBayes. But I have found many stick with Stan and Julia, not what I expected when I started this work in 2011.

Vaibhav, as we discussed earlier, if we go ahead with a StanJulia/DiffEqBayesStan, I will give you ownership in StanJulia and make you the primary author of DiffEqBayesStan (and that is the truth!). The very first section of the readme will clearly state that DiffEqBayesStan is a simplified version (in terms of dependencies) of DiffEqBayes. Time will tell, but I would consider myself the primary maintainer.

Rob

**Comment by Vaibhavdixit02** [comment]
@goedman let's go ahead with it, I see the value and there is hardly any downside as discussed above, will be exciting! Sorry to have slowed you down with my concerns.

**Comment by goedman** [comment]
Hi Vaibhav, thanks for your support, you've certainly not slowed me down! I'll prepare the initial version of the repo over the next couple of days.

**Comment by goedman** [comment]
@Vaibhavdixit02 , I did send you an invite to StanJulia. Of course up to you if you wanna accept this! Or I could send you an invite to just DiffEqBayesStan.jl a bit later on.

A local version of DiffEqBayesStan is basically working. I like to make a few more updates, the most important ones are:

1. Switching the tests to Tables.jl based chains (I don't think right now AxisArrays.jl in MCMCChains runs on J1.7 & 1.8).
2. Add the  DEB tests as examples to Stan.jl (which I use to test all of StanJulia on 1.6, 1.7 & nightly).

And also, slightly longer term:

3. I would love to add a SIR model example.
4. I'm looking into a way of making the code in `stan_inference()` easier to grasp by creating a step-by-step example script documenting the key steps like generating the ODE model code, generating constraints on the parameters and generating the priors (maybe as a Pluto notebook). This is part of `how far can we push?` code like this:
```
  if isnothing(diffeq_string)
    sys = ModelingToolkit.modelingtoolkitize(prob)
    length_of_parameter = length(ModelingToolkit.parameters(sys)) + sample_u0 * length(save_idxs)
  else
    length_of_parameter = length(prob.p) + sample_u0 * length(save_idxs)
  end
```
5. Better understand the `save_idxs` related lines in `stan_inference()`.

Rob

**Comment by Vaibhavdixit02** [comment]
Hey @goedman I didn't receive the invitation unfortunately, can you send it again?

**Comment by goedman** [comment]
Just redid it.

<img width="1783" alt="Screen Shot 2021-07-16 at 10 52 28" src="https://user-images.githubusercontent.com/52200/125982308-64b2c03c-e5c0-4d8a-b0aa-e0f08ca6fd09.png">
