### ISSUE TITLE
Turing inference BoundsError when save_idxs is single value

### ISSUE THREAD

**Issue by brendandaisy** [SciML/DiffEqBayes.jl#235]
I get a BoundsError when calling `turing_inference` when `save_idxs` is a single digit. A minimum code for this from the tutorial:

```julia
using ParameterizedFunctions, OrdinaryDiffEq, RecursiveArrayTools, Distributions
using DiffEqBayes

f1 = @ode_def LotkaVolterra 
 dx = a*x - x*y
 dy = -3*y + x*y
end a

p = [1.5]
u0 = [1.0,1.0]
tspan = (0.0,10.0)
prob1 = ODEProblem(f1,u0,tspan,p)

σ = 0.01                         # noise, fixed for now
t = collect(1.:10.)   # observation times
sol = solve(prob1,Tsit5())
priors = [Normal(1.5, 1)]
randomized = VectorOfArray([(sol(t[i]) + σ * randn(2)) for i in 1:length(t)])
data = convert(Array,randomized)

bayesian_result_turing = turing_inference(prob1,Tsit5(),t,data,priors; save_idxs=2)
```

which gives me the error `ERROR: BoundsError: attempt to access Tuple{Int64} at index [2]`.  

Presumably, this is from the `size(sol, 2)` check within the model macro. But this seems like an unnecessary failure for a pretty straightforward use case.

Apologies if I'm missing something obvious here, I'm relatively new to Julia.

**Comment by Vaibhavdixit02** [comment]
Use an array instead of passing the value, `save_idxs = [2]` that should fix it

**Comment by brendandaisy** [comment]
Doing this gives me a DimensionMismatch error, because now the block
```julia
if ndims(sol) == 1
            x ~ likelihood(Array(sol), theta, Inf, σ)
...
```
will never be true. I can get around this with the call
```julia
bayesian_result_turing = turing_inference(prob1,Tsit5(),t,reshape(data[2,:], (1,10)),priors; save_idxs=[2])
```
but this seems unintuitive. Maybe there is an easy way to allow 1-dimensional data/ode solutions?

Thanks for getting back to me!

**Comment by ChrisRackauckas** [comment]
This case can be handled, it's just a little nasty so it needs specific branches, and it sounds like that branch needs fixing 😅

**Comment by brendandaisy** [comment]
Ah OK, I see the example in the README file now 🤦‍♀️It would maybe be nice to have that branch work though, to avoid having to specify 1-dimensional multivariate likelihoods for example.
