### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by MaAl13** [SciML/DiffEqBayes.jl#237]
Hi, i want to install DiffEqBayes. However, if i want to add it in the Package environment i get the following dependency error:
ERROR: Unsatisfiable requirements detected for package Turing [fce5fe82]:
 Turing [fce5fe82] log:
 ├─possible versions are: 0.5.0-0.21.2 or uninstalled
 ├─restricted by compatibility requirements with DiffEqBayes [ebbdde9d] to versions: 0.5.0-0.16.6
 │ └─DiffEqBayes [ebbdde9d] log:
 │   ├─possible versions are: 0.8.0-2.26.0 or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.8.0-2.26.0
 │   └─restricted by compatibility requirements with RecursiveArrayTools [731186ca] to versions: 2.4.0-2.26.0 or uninstalled, leaving only versions: 2.4.0-2.26.0
 │     └─RecursiveArrayTools [731186ca] log:
 │       ├─possible versions are: 0.16.0-2.29.0 or uninstalled
 │       ├─restricted by compatibility requirements with DiffEqParamEstim [1130ab10] to versions: 0.16.0-2.29.0
 │       │ └─DiffEqParamEstim [1130ab10] log:
 │       │   ├─possible versions are: 1.2.0-1.23.0 or uninstalled
 │       │   ├─restricted to versions * by an explicit requirement, leaving only versions 1.2.0-1.23.0
 │       │   └─restricted by compatibility requirements with RecursiveArrayTools [731186ca] to versions: 1.12.0-1.23.0 or uninstalled, leaving only versions: 1.12.0-1.23.0
 │       │     └─RecursiveArrayTools [731186ca] log: see above
 │       └─restricted by compatibility requirements with DiffEqGPU [071ae1c0] to versions: 2.0.0-2.29.0
 │         └─DiffEqGPU [071ae1c0] log:
 │           ├─possible versions are: 0.1.0-1.16.0 or uninstalled
 │           ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-1.16.0
 │           ├─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.1.0-1.3.0, 1.9.0-1.16.0] or uninstalled, leaving only versions: [0.1.0-1.3.0, 1.9.0-1.16.0]
 │           │ └─CUDA [052768ef] log:
 │           │   ├─possible versions are: 0.1.0-3.10.0 or uninstalled
 │           │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-3.10.0
 │           │   ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-3.10.0] or uninstalled, leaving only versions: [2.3.0, 2.5.0-3.10.0]
 │           │   ├─restricted by compatibility requirements with DiffEqGPU [071ae1c0] to versions: [1.0.0-2.6.3, 3.1.0-3.10.0], leaving only versions: [2.3.0, 2.5.0-2.6.3, 3.1.0-3.10.0]
 │           │   │ └─DiffEqGPU [071ae1c0] log: see above
 │           │   ├─restricted by compatibility requirements with Transformers [21ca0261] to versions: [2.4.0-2.6.3, 3.2.0-3.10.0], leaving only versions: [2.5.0-2.6.3, 3.2.0-3.10.0]
 │           │   │ └─Transformers [21ca0261] log:
 │           │   │   ├─possible versions are: 0.0.1-0.1.16 or uninstalled
 │           │   │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.1.16
 │           │   │   ├─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.0.1-0.1.3, 0.1.8-0.1.16] or uninstalled, leaving only versions: [0.0.1-0.1.3, 0.1.8-0.1.16]
 │           │   │   │ └─CUDA [052768ef] log: see above
 │           │   │   ├─restricted by compatibility requirements with CUDAnative [be33ccc6] to versions: [0.0.6-0.1.1, 0.1.4-0.1.16] or uninstalled, leaving only versions: [0.0.6-0.1.1, 0.1.8-0.1.16]
 │           │   │   │ └─CUDAnative [be33ccc6] log:
 │           │   │   │   ├─possible versions are: 0.7.0-3.2.0 or uninstalled
 │           │   │   │   └─restricted by julia compatibility requirements to versions: uninstalled
 │           │   │   ├─restricted by compatibility requirements with Adapt [79e6a3ab] to versions: [0.0.1-0.0.3, 0.1.4-0.1.16] or uninstalled, leaving only versions: 0.1.8-0.1.16
 │           │   │   │ └─Adapt [79e6a3ab] log:
 │           │   │   │   ├─possible versions are: 0.3.0-3.3.3 or uninstalled
 │           │   │   │   ├─restricted by compatibility requirements with CUDA [052768ef] to versions: 2.2.0-3.3.3
 │           │   │   │   │ └─CUDA [052768ef] log: see above
 │           │   │   │   ├─restricted by compatibility requirements with Transformers [21ca0261] to versions: 3.2.0-3.3.3
 │           │   │   │   │ └─Transformers [21ca0261] log: see above
 │           │   │   │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: 3.3.0-3.3.3
 │           │   │   │     └─CUDA [052768ef] log: see above
 │           │   │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.0.1-0.1.3, 0.1.12-0.1.16] or uninstalled, leaving only versions: 0.1.12-0.1.16
 │           │   │     └─CUDA [052768ef] log: see above
 │           │   └─restricted by compatibility requirements with LLVM [929cbde3] to versions: 3.3.3-3.10.0 or uninstalled, leaving only versions: 3.3.3-3.10.0
 │           │     └─LLVM [929cbde3] log:
 │           │       ├─possible versions are: 0.9.0-4.13.0 or uninstalled
 │           │       ├─restricted by julia compatibility requirements to versions: 4.0.0-4.13.0 or uninstalled
 │           │       └─restricted by compatibility requirements with CUDA [052768ef] to versions: 3.0.0-4.13.0, leaving only versions: 4.0.0-4.13.0
 │           │         └─CUDA [052768ef] log: see above
 │           ├─restricted by compatibility requirements with CUDAnative [be33ccc6] to versions: 1.4.0-1.16.0 or uninstalled, leaving only versions: 1.9.0-1.16.0
 │           │ └─CUDAnative [be33ccc6] log: see above
 │           └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.1.0-1.3.0, 1.12.0-1.16.0] or uninstalled, leaving only versions: 1.12.0-1.16.0
 │             └─CUDA [052768ef] log: see above
 ├─restricted by compatibility requirements with MCMCChain [1671dc4f] to versions: 0.6.11-0.21.2 or uninstalled, leaving only versions: 0.6.11-0.16.6
 │ └─MCMCChain [1671dc4f] log:
 │   ├─possible versions are: 0.1.0-0.2.3 or uninstalled
 │   └─restricted by julia compatibility requirements to versions: uninstalled
 ├─restricted by compatibility requirements with Requires [ae029012] to versions: 0.8.0-0.21.2 or uninstalled, leaving only versions: 0.8.0-0.16.6
 │ └─Requires [ae029012] log:
 │   ├─possible versions are: 0.5.0-1.3.0 or uninstalled
 │   ├─restricted by compatibility requirements with CUDA [052768ef] to versions: 0.5.0-1.3.0
 │   │ └─CUDA [052768ef] log: see above
 │   └─restricted by compatibility requirements with Transformers [21ca0261] to versions: 1.0.0-1.3.0
 │     └─Transformers [21ca0261] log: see above
 ├─restricted by compatibility requirements with AdvancedPS [576499cb] to versions: [0.5.0-0.15.1, 0.20.0-0.21.2] or uninstalled, leaving only versions: 0.8.0-0.15.1
 │ └─AdvancedPS [576499cb] log:
 │   ├─possible versions are: 0.1.0-0.3.8 or uninstalled
 │   └─restricted by compatibility requirements with Libtask [6f1fad26] to versions: 0.3.0-0.3.8 or uninstalled
 │     └─Libtask [6f1fad26] log:
 │       ├─possible versions are: 0.1.1-0.7.3 or uninstalled
 │       ├─restricted by compatibility requirements with Libtask_jll [3ae2931a] to versions: [0.1.1-0.4.2, 0.6.0-0.7.3] or uninstalled
 │       │ └─Libtask_jll [3ae2931a] log:
 │       │   ├─possible versions are: 0.3.0-0.5.1 or uninstalled
 │       │   └─restricted by julia compatibility requirements to versions: [0.3.0-0.3.2, 0.5.0-0.5.1] or uninstalled
 │       └─restricted by compatibility requirements with Turing [fce5fe82] to versions: 0.1.1-0.5.3, leaving only versions: 0.1.1-0.4.2
 │         └─Turing [fce5fe82] log: see above
 └─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: [0.5.0-0.5.1, 0.15.4-0.21.2] or uninstalled — no versions left
   └─SpecialFunctions [276daf66] log:
     ├─possible versions are: 0.7.0-2.1.5 or uninstalled
     ├─restricted by compatibility requirements with Distributions [31c24e10] to versions: 0.7.0-2.1.5
     │ └─Distributions [31c24e10] log:
     │   ├─possible versions are: 0.16.0-0.25.59 or uninstalled
     │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.16.0-0.25.59
     │   └─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: 0.24.4-0.25.59 or uninstalled, leaving only versions: 0.24.4-0.25.59
     │     └─SpecialFunctions [276daf66] log: see above
     ├─restricted by compatibility requirements with KernelAbstractions [63c18a36] to versions: 0.10.0-2.1.5
     │ └─KernelAbstractions [63c18a36] log:
     │   ├─possible versions are: 0.1.0-0.8.1 or uninstalled
     │   ├─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.1.0-0.2.6, 0.4.5-0.8.1] or uninstalled
     │   │ └─CUDA [052768ef] log: see above
     │   ├─restricted by compatibility requirements with CUDAnative [be33ccc6] to versions: 0.3.0-0.8.1 or uninstalled, leaving only versions: 0.4.5-0.8.1 or uninstalled
     │   │ └─CUDAnative [be33ccc6] log: see above
     │   ├─restricted by compatibility requirements with DiffEqGPU [071ae1c0] to versions: [0.2.0-0.4.6, 0.5.5-0.7.2], leaving only versions: [0.4.5-0.4.6, 0.5.5-0.7.2]
     │   │ └─DiffEqGPU [071ae1c0] log: see above
     │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.1.0-0.2.6, 0.6.0-0.8.1] or uninstalled, leaving only versions: 0.6.0-0.7.2
     │     └─CUDA [052768ef] log: see above
     └─restricted by compatibility requirements with CUDA [052768ef] to versions: 1.3.0-2.1.5
       └─CUDA [052768ef] log: see above

**Comment by ChrisRackauckas** [comment]
I'm not sure this library has been looked at in more than a year. I think some dependencies have updated and we'll need to update a few things to support Julia v1.6+. 

@Vaibhavdixit02 I did https://github.com/SciML/DiffEqBayes.jl/pull/238 as a test to see what would happen if we allow the newer versions.

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02 I saw you tagged a few things, was this solved?

**Comment by Vaibhavdixit02** [comment]
No it isn't, I will take a look at it soon, it's on my agenda

**Comment by Vaibhavdixit02** [comment]
It should be good now, please update the package to v3.0.0 and try @MaAl13, let us know if the issue still persists
