### ISSUE TITLE
Support for sampling from multiple chains is missing from `turing_inference`

### ISSUE THREAD

**Issue by saumil-sh** [SciML/DiffEqBayes.jl#306]
`sample()` from `Turing.jl` [supports sampling from multiple shains](https://turinglang.org/v0.26/docs/using-turing/guide#sampling-multiple-chains). These arguments are missing [in `turing_inference`](https://github.com/SciML/DiffEqBayes.jl/blob/master/src/turing_inference.jl#L58), this package's `Turing.jl` interface. I am willing to work on this functionality. May I submit a pull request?

**Comment by saumil-sh** [comment]
I went ahead an opened a [pull request](https://github.com/SciML/DiffEqBayes.jl/pull/307), I hope it is okay 😄

**Comment by Vaibhavdixit02** [comment]
That's great, thanks for chipping in!
